kind: pipeline
name: default

steps:
- name: test
  image: compose:1.23.2
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - echo "Creating data directory"  
  - mkdir -p $DRONE_BUILD_DIR/data/donations
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
