
build:
  ci:
    - echo "Creating data directory"
	- mkdir -p $SHIPPABLE_BUILD_DIR/data/donations
	- mkdir -p $SHIPPABLE_BUILD_DIR/data/unverified_donations 
	- mkdir -p $SHIPPABLE_BUILD_DIR/data/quarantine
	- cd $SHIPPABLE_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml build
    - cd $SHIPPABLE_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
