language: generic
services:
  - docker
env:
  - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
before_install: |
  echo "Updating docker-compose to version 1.24.1" \
  && curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /tmp/docker-compose \
  && sudo rm /usr/local/bin/docker-compose \
  && sudo mv /tmp/docker-compose /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose \
  && cd $TRAVIS_BUILD_DIR \
  && echo "Cloning imagemonkey-labels" \
  && git clone https://github.com/bbernhard/imagemonkey-labels.git wordlists \
  && rm -f $TRAVIS_BUILD_DIR/wordlists/.travis.yml \
  && echo "Creating avatars directory" \
  && mkdir -p $TRAVIS_BUILD_DIR/avatars \
  && cp $TRAVIS_BUILD_DIR/img/default.png $TRAVIS_BUILD_DIR/avatars/default.png \
  && echo "Creating data directory" \
  && mkdir -p $TRAVIS_BUILD_DIR/data/donations \
  && mkdir -p $TRAVIS_BUILD_DIR/data/quarantine \
  && mkdir -p $TRAVIS_BUILD_DIR/data/unverified_donations \
  && echo "Downloading existing images (for caching)" \
  && docker pull bbernhard/imagemonkey-api:latest \
  && docker pull bbernhard/imagemonkey-db:latest \
  && docker pull bbernhard/imagemonkey-testing:latest \
  && docker-compose -f env/docker/docker-compose.travis.yml build --parallel

jobs:
  include:
    - stage: test
      script: cd $TRAVIS_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
      env:
        - TEST_MODE=only-ui
    - # stage name not required, will continue to use `test`
      script: cd $TRAVIS_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
      env:
        - TEST_MODE=only-api
    - # stage name not required, will continue to use `test`
      script: cd $TRAVIS_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
      env:  
        - TEST_MODE=only-unittest


#script:
#  cd $TRAVIS_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
