version: "3"
services:
  db:
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile.postgres
      args:
        - MONKEY_DB_PASSWORD="dbRuwMUo4Nfhs5hmMxhk"
    environment:
      - POSTGRES_PASSWORD="example"
      - POSTGRES_DB="imagemonkey"

  web:
    restart: always
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.web
      args:
        - MONKEY_DB_PASSWORD="dbRuwMUo4Nfhs5hmMxhk"
        - X_CLIENT_ID="de61ac57c1889941a9200ecff2c8eeeb390350c9813e13e8d439516dd389127f"
        - X_CLIENT_SECRET="ef2748970181a4d3b0e5892f755f60a1cb24980c66d880e971542e8f1aae8958"
        - JWT_SECRET="e0e8cb89320d6fd5b46eeb32c22cd3f5d657eb8eafcbed1cafe24a03a6ca47f7"
  #api:
  #  restart: always
  #  build:
  #    context: "../../"
  #    dockerfile: env/docker/Dockerfile.api
  #    args:
  #      - MONKEY_DB_PASSWORD="dbRuwMUo4Nfhs5hmMxhk" 